model.library {
  server.port = 8090
  runtime.executor = "stub"
  run-config.kafka-defaults {
    bootstrap-servers = "localhost:9092"
    topic = "simulation.${simulationId}.${coordinatorId}"
    consumer-group = "${modelInstanceId}"
    security-protocol = "PLAINTEXT"
    sasl-mechanism = ""
  }
}